# Arrays

## Códigos do Terminal

In [ ]:
julia> struct aluno
           nome::String
           matricula::Int64
           nota_p1::Float64
           nota_p2::Float64
           nota_p3::Float64
       end

julia> x = aluno("Edson", 123, 6.0, 6.5, 5.5)
aluno("Edson", 123, 6.0, 6.5, 5.5)

julia> x.

matricula
nome
nota_p1
nota_p2
nota_p3
julia> x.

matricula
nome
nota_p1
nota_p2
nota_p3
julia> x.

matricula
nome
nota_p1
nota_p2
nota_p3
julia> x.

matricula
nome     
nota_p1  
nota_p2
nota_p3
julia> x.matricula
123

julia> x.nome
"Edson"

julia> x.nota_p1
6.0

julia> y=aluno("Gean", 999, 10.0, 10.0, 8.0)
aluno("Gean", 999, 10.0, 10.0, 8.0)

julia> y.nome
"Gean"

julia> y.nota_p2
10.0

julia> u = [x,y]
2-element Vector{aluno}:
 aluno("Edson", 123, 6.0, 6.5, 5.5)
 aluno("Gean", 999, 10.0, 10.0, 8.0)

julia> x.
       x
ERROR: type aluno has no field x
Stacktrace:
 [1] getproperty(x::aluno, f::Symbol)
   @ Base .\Base.jl:37
 [2] top-level scope  
   @ REPL[10]:1

julia> x.
matricula
nome
nota_p1
nota_p2
nota_p3
julia> x.nome
"Edson"

julia> typeof(u)
Vector{aluno} (alias for Array{aluno, 1})

julia> u[1]
aluno("Edson", 123, 6.0, 6.5, 5.5)

julia> u[2]
aluno("Gean", 999, 10.0, 10.0, 8.0)

julia> u[6]
ERROR: BoundsError: attempt to access 2-element Vector{aluno} at index [6]
Stacktrace:
 [1] getindex(A::Vector{aluno}, i1::Int64)
   @ Base .\essentials.jl:13
 [2] top-level scope
   @ REPL[15]:1

julia> u
2-element Vector{aluno}:
 aluno("Edson", 123, 6.0, 6.5, 5.5)
 aluno("Gean", 999, 10.0, 10.0, 8.0)

julia> u
2-element Vector{aluno}:
 aluno("Edson", 123, 6.0, 6.5, 5.5)
 aluno("Gean", 999, 10.0, 10.0, 8.0)

julia> x
aluno("Edson", 123, 6.0, 6.5, 5.5)

julia> lenght(u)
ERROR: UndefVarError: `lenght` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[18]:1

julia> length(u)
2

julia> size(u)
(2,)

julia> x
aluno("Edson", 123, 6.0, 6.5, 5.5)

julia> x.nota_p1 = 6.5
ERROR: setfield!: immutable struct of type aluno cannot be changed
Stacktrace:
 [1] setproperty!(x::aluno, f::Symbol, v::Float64)
   @ Base .\Base.jl:41
 [2] top-level scope
   @ REPL[22]:1

julia> x = aluno("Edson", 123, 6.5, 6.5, 5.5)
aluno("Edson", 123, 6.5, 6.5, 5.5)

julia> u
2-element Vector{aluno}:
 aluno("Edson", 123, 6.0, 6.5, 5.5)
 aluno("Gean", 999, 10.0, 10.0, 8.0)

julia> v = u
2-element Vector{aluno}:
 aluno("Edson", 123, 6.0, 6.5, 5.5)
 aluno("Gean", 999, 10.0, 10.0, 8.0)

julia> u[1]=x

In [ ]:
julia> mutable struct aluno
           nome::String
           matricula::Int64
               nota_p1::Float64
           nota_p2::Float64
               nota_p3::Float64
       end

julia> mutable struct aluno
           nome::String
           matricula::Int64
           nota_p1::Float64
               nota_p2::Float64
           nota_p3::Float64
       end

julia> x = ("Saulo", 2931, 10.0, 10.0, 9.5)
("Saulo", 2931, 10.0, 10.0, 9.5)

julia> x
("Saulo", 2931, 10.0, 10.0, 9.5)

julia> x = aluno("Saulo", 2931, 10.0, 10.0, 10.0)
aluno("Saulo", 2931, 10.0, 10.0, 10.0)

julia> x=aluno("Guilherme", 456, 10.0, 10.0, -2.0)
aluno("Guilherme", 456, 10.0, 10.0, -2.0)

julia> x.nota_p3 = -5.0
-5.0

julia> x
aluno("Guilherme", 456, 10.0, 10.0, -5.0)

julia> y=x
aluno("Guilherme", 456, 10.0, 10.0, -5.0)

julia> x.nota_p1 = 8.0
8.0

julia> y
aluno("Guilherme", 456, 8.0, 10.0, -5.0)

julia> u=[x,x]
2-element Vector{aluno}:
 aluno("Guilherme", 456, 8.0, 10.0, -5.0)
 aluno("Guilherme", 456, 8.0, 10.0, -5.0)

julia> u[2].nota_p3=10.0
10.0

julia> u
2-element Vector{aluno}:
 aluno("Guilherme", 456, 8.0, 10.0, 10.0)
 aluno("Guilherme", 456, 8.0, 10.0, 10.0)

julia> w = ["oi", 1, 9.0]
3-element Vector{Any}:
  "oi"
 1
 9.0

julia> TypeOf(w)
ERROR: UndefVarError: `TypeOf` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[16]:1

julia> typeof(w)
Vector{Any} (alias for Array{Any, 1})

julia> mutable struct aluno
           nome::String
           matricula::Int64
               nota_p1::Float64
           nota_p2::Float64
           nota_p3::Float64
           end

In [1]:
julia> h=[1,9.0]
2-element Vector{Float64}:
 1.0
 9.0

julia> h=[Int64(1), 9.0]
2-element Vector{Float64}:
 1.0
 9.0

julia> j = [1, 9]
2-element Vector{Int64}:
 1
 9

julia> h::Vector{Any} = [1,9.0]
ERROR: cannot set type for global Main.h. It already has a value or is already set to a different type.
Stacktrace:
 [1] top-level scope
   @ REPL[22]:1

julia> [[1,2]  [4,5]  [7,8]]
2×3 Matrix{Int64}:
 1  4  7
 2  5  8

julia> A[1]=2.0
ERROR: UndefVarError: `A` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[24]:1

julia> A[1,1]=20
ERROR: UndefVarError: `A` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[25]:1

julia> A=[[1,2]  [4,5]  [7,8]]
2×3 Matrix{Int64}:
 1  4  7
 2  5  8

julia> A[1,1]=20
20

julia> A
2×3 Matrix{Int64}:
 20  4  7
  2  5  8

julia> A[1,1]=1
1

julia> A
2×3 Matrix{Int64}:
 1  4  7
 2  5  8

julia> A[1]=[2,3]
ERROR: MethodError: Cannot `convert` an object of type Vector{Int64} to an object of type Int64

Closest candidates are:
  convert(::Type{T}, ::T) where T<:Number
   @ Base number.jl:6
  convert(::Type{T}, ::T) where T
   @ Base Base.jl:84
  convert(::Type{T}, ::AbstractChar) where T<:Number
   @ Base char.jl:185
  ...

Stacktrace:
 [1] setindex!(A::Matrix{Int64}, x::Vector{Int64}, i1::Int64)
   @ Base .\array.jl:1021
 [2] top-level scope
   @ REPL[31]:1

julia> A[1]
1

julia> A[2]
2

julia> A[3]
4

julia> A[4]
5

julia> A=[[1,2]  [4,5]  [7,8]]
2×3 Matrix{Int64}:
 1  4  7
 2  5  8

julia> size(A)
(2, 3)

julia> length(A)
6

julia> A[3,1]
ERROR: BoundsError: attempt to access 2×3 Matrix{Int64} at index [3, 1]
Stacktrace:
 [1] getindex(::Matrix{Int64}, ::Int64, ::Int64)
   @ Base .\essentials.jl:14
 [2] top-level scope
   @ REPL[39]:1

julia> A[1,3]=200
200

julia> A
2×3 Matrix{Int64}:
 1  4  200
 2  5    8

julia> zeros(3)
3-element Vector{Float64}:
 0.0
 0.0
 0.0

julia> zeros((3,2))
3×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
 0.0  0.0

julia> zeros(Int64, (3,2)
       zeros(Int64, (3,2))
ERROR: ParseError:
# Error @ REPL[44]:2:1
zeros(Int64, (3,2)
zeros(Int64, (3,2))
└───────────────┘ ── Expected `)`
Stacktrace:
 [1] top-level scope
   @ none:1

julia> zeros(Int64, (3,2))
3×2 Matrix{Int64}:
 0  0
 0  0
 0  0

julia> using LinearAlgebra

julia> Marix{Int64}(I, 7, 8)
ERROR: UndefVarError: `Marix` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[47]:1

julia> Matrix{Float64}(I,5,5)
5×5 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  1.0

julia> rand(Float64,9,8)
9×8 Matrix{Float64}:
 0.247998  0.331503    0.701153   0.0982563  0.755115  0.20712    0.406274   0.579729
 0.51218   0.925055    0.731429   0.312677   0.679894  0.566339   0.408991   0.289465
 0.557214  0.00042413  0.166076   0.484332   0.344888  0.445354   0.329089   0.469326
 0.631691  0.942297    0.58712    0.0295692  0.803058  0.458133   0.646908   0.639113
 0.389896  0.165209    0.801451   0.636842   0.295202  0.173386   0.147931   0.266574
 0.710641  0.728272    0.416422   0.661509   0.662975  0.142683   0.948257   0.977418
 0.35872   0.237152    0.405036   0.70051    0.508666  0.0732016  0.0674157  0.539756
 0.778282  0.338083    0.704678   0.0279231  0.407901  0.760241   0.16474    0.942583
 0.241918  0.39599     0.0514333  0.373615   0.433685  0.716115   0.903963   0.184927

julia> randn(Float64, 3, 3)
3×3 Matrix{Float64}:
 -0.923024  -0.267357   0.557572
  0.906102   0.153075  -0.429209
 -1.03127    0.385121  -0.748085

julia>

UndefVarError: UndefVarError: `element` not defined